# Generated by Django 4.1.1 on 2023-01-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaialable',
            new_name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='1999-12-12'),
            preserve_default=False,
        ),
    ]
