# Generated by Django 4.1.1 on 2023-02-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_app',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default='03-05-1999', on_delete=django.db.models.deletion.CASCADE, to='cart_app.cart'),
            preserve_default=False,
        ),
    ]
